"use client";
import {useEffect,useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import {Activity,AlertTriangle,BatteryCharging,Building2,Clock3,Download,Info,Layers3,Pause,Play,RefreshCw,RotateCcw,Snowflake,Sun,Waypoints,Zap} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Area,AreaChart,CartesianGrid,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {clock} from '@/lib/twin/engine';
import {flexDefaults,flexScenarios,simulateFlex,withScenario,type AssetKind,type FlexConfig,type FlexScenarioId} from '@/lib/twin/flex-engine';

const EnergyHubScene=dynamic(()=>import('./EnergyHubScene'),{ssr:false,loading:()=> <div className="error-fallback">Preparing the energy hub…</div>});
const n=(v:number,d=1)=>v.toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d});
const statusClass=(state:string)=>state==='critical'||state==='stale'?'red':state==='warning'||state==='limited'?'amber':'green';
const assetIcon=(kind:AssetKind)=>kind==='battery'?BatteryCharging:kind==='ev'?Zap:kind==='cold'?Snowflake:kind==='hvac'?Building2:Activity;

function Metric({label,value,unit,note,icon:Icon,color=''}:{label:string;value:string|number;unit?:string;note:string;icon:any;color?:string}){return <div className="metric"><div className="metric-label">{label}<Icon/></div><div className={`metric-value ${color}`}>{value}<span>{unit}</span></div><div className="metric-note">{note}</div></div>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="inspector-stat"><span>{label}</span><b>{value}</b></div>}
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
function download(name:string,content:string,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

export default function EnergyHubApp(){
 const [config,setConfig]=useState<FlexConfig>(flexDefaults);const [time,setTime]=useState(765);const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState(10);const [showFlows,setShowFlows]=useState(true);const [selected,setSelected]=useState('hub');const [resetCamera,setResetCamera]=useState(0);const [tab,setTab]=useState('operations');
 const result=useMemo(()=>simulateFlex(config),[config]);const frame=result.frames[Math.min(1439,Math.floor(time))];const currentScenario=flexScenarios.find(s=>s.id===config.scenario)!;
 useEffect(()=>{if(!playing)return;let last=performance.now();const id=setInterval(()=>{const now=performance.now(),dt=(now-last)/1000;last=now;setTime(t=>{const next=t+dt*speed;if(next>=1439){setPlaying(false);return 1439}return next})},50);return()=>clearInterval(id)},[playing,speed]);
 const set=(patch:Partial<FlexConfig>)=>{setConfig(c=>({...c,...patch}));setPlaying(false)};const chooseScenario=(id:FlexScenarioId)=>{setConfig(c=>withScenario(c,id));const s=flexScenarios.find(x=>x.id===id)!;setTime(Math.max(0,s.start-15));setSelected('hub');setPlaying(false)};
 const selectedAsset=frame.assets.find(a=>a.id===selected);const alarms=result.events.filter(e=>e.time<=time).slice(-30).reverse();
 const chartData=useMemo(()=>result.frames.filter((_,i)=>i%5===0).map(f=>({time:clock(f.time),baseline:f.baselineGrid,controlled:f.controlledGrid,request:f.requestKw,available:f.availableKw,rebound:f.reboundKw})),[result]);
 const eventData=useMemo(()=>result.frames.slice(Math.max(0,config.start-30),Math.min(1440,config.start+config.duration+120)).filter((_,i)=>i%2===0).map(f=>({time:clock(f.time),request:f.requestKw,delivered:f.deliveredKw,available:f.availableKw,shortfall:f.shortfallKw,rebound:f.reboundKw})),[result,config]);
 const dispatchData=frame.assets.map(a=>({name:a.name.replace(' charging fleet','').replace('Flexible ','').replace('Building ',''),available:a.availableDownKw,dispatch:a.dispatchedKw}));
 const eventFrames=result.frames.slice(config.start,Math.min(1440,config.start+config.duration));const deliveredKwh=eventFrames.reduce((a,f)=>a+f.deliveredKw/60,0);const requestedKwh=eventFrames.reduce((a,f)=>a+f.requestKw/60,0);const compliance=requestedKwh?deliveredKwh/requestedKwh*100:100;
 const exportCsv=()=>download('energy-hub-flexibility.csv','time,baseline_grid_kw,controlled_grid_kw,flex_request_kw,available_flex_kw,delivered_flex_kw,shortfall_kw,rebound_kw,battery_soc_pct,battery_temp_c,cold_store_temp_c,telemetry_age_s\n'+result.frames.map(f=>[clock(f.time),f.baselineGrid,f.controlledGrid,f.requestKw,f.availableKw,f.deliveredKw,f.shortfallKw,f.reboundKw,f.batterySoc,f.batteryTemp,f.coldTemp,f.telemetryAgeSec].join(',')).join('\n'));
 return <div className="shell flex-v2">
  <header className="header"><div className="brand"><div className="brandmark"><Waypoints/></div><div><div className="brandname">FUTURE EV / <span>ENERGY TWIN</span></div><small>V2 · Energy flexibility digital twin</small></div><div className="divider"/><span className="badge">ENERGY HUB</span></div><div className="header-actions"><a className="btn" href={`${BASE_PATH}/v1/`}>Open preserved V1</a><button className="btn" onClick={exportCsv}><Download/>Export</button></div></header>
  <main className="workspace">
   <div className="intro"><div><div className="eyebrow">ENERGY FLEXIBILITY / DIGITAL TWIN</div><h1>From BEMS load management to dispatchable site flexibility</h1><p>One site, multiple flexible assets, explicit operating constraints, telemetry quality and recovery after a grid event.</p></div><div className="intro-right"><span className="status-tag"><i/>Deterministic simulation</span><span className="badge">Synthetic operational data</span></div></div>
   <div className="metrics">
    <Metric label="Available down-flex" value={n(frame.availableKw,0)} unit="kW" note={`30 min envelope ${n(frame.envelope30,0)} kW`} icon={Layers3} color={frame.availableKw>=config.requestKw?'green':'amber'}/>
    <Metric label="Flex commitment" value={n(frame.requestKw,0)} unit="kW" note={frame.requestKw?`${clock(config.start)}–${clock(config.start+config.duration)}`:'No active request'} icon={Zap}/>
    <Metric label="Delivered now" value={n(frame.deliveredKw,0)} unit="kW" note={frame.shortfallKw>1?`${n(frame.shortfallKw,0)} kW shortfall`:'Protected constraints respected'} icon={Activity} color={frame.shortfallKw>1?'red':frame.requestKw?'green':''}/>
    <Metric label="Grid import" value={n(frame.controlledGrid,0)} unit="kW" note={`Baseline ${n(frame.baselineGrid,0)} kW · limit ${config.grid} kW`} icon={Waypoints} color={frame.controlledGrid>config.grid?'red':''}/>
    <Metric label="Recovery / rebound" value={n(frame.reboundKw,0)} unit="kW" note={`${n(frame.deferredKwh,1)} kWh still deferred`} icon={RefreshCw} color={frame.reboundKw?'amber':''}/>
   </div>
   <div className="main-grid">
    <aside className="left-panel"><div className="panel panel-body"><div className="section-label">Flexibility scenario</div><div className="scenario-list">{flexScenarios.map(s=><button key={s.id} className={`scenario-choice ${config.scenario===s.id?'active':''}`} onClick={()=>chooseScenario(s.id)}><b>{s.name}</b><span>{s.description}</span></button>)}</div><div className="sepline"/><div className="section-label">Commitment</div><div className="field"><label>Requested reduction <b>{config.requestKw} kW</b></label><Slider min={20} max={140} step={5} value={[config.requestKw]} onValueChange={([requestKw])=>set({requestKw})}/></div><div className="field"><label>Duration <b>{config.duration} min</b></label><Slider min={10} max={90} step={5} value={[config.duration]} onValueChange={([duration])=>set({duration})}/></div><div className="field"><label>Grid connection <b>{config.grid} kW</b></label><Slider min={100} max={220} step={5} value={[config.grid]} onValueChange={([grid])=>set({grid})}/></div><div className="field"><label>Solar peak <b>{config.solar} kWp</b></label><Slider min={40} max={160} step={5} value={[config.solar]} onValueChange={([solar])=>set({solar})}/></div><div className="scenario-note"><b>{currentScenario.name}</b><br/>{currentScenario.description}</div><a className="btn" href={`${BASE_PATH}/v1/`}><RotateCcw/>Compare with original BEMS</a></div></aside>
    <section className="centre">
     <div className="scene-panel"><EnergyHubScene frame={frame} showFlows={showFlows} onSelect={setSelected} reset={resetCamera}/><div className="scene-top"><div><div className="scene-title">Commercial energy hub · operational view</div><div className="scene-sub">Select an asset to inspect its flexibility, limits and telemetry state</div></div><div className="scene-tools"><button className="btn icon" title="Toggle energy flows" onClick={()=>setShowFlows(v=>!v)}><Activity/></button><button className="btn icon" title="Reset camera" onClick={()=>setResetCamera(v=>v+1)}><RotateCcw/></button></div></div><div className="scene-bottom"><div className="legend"><span><i style={{background:'#70e3bb'}}/>EV</span><span><i style={{background:'#66c1e8'}}/>Battery</span><span><i style={{background:'#f6c66b'}}/>Solar</span><span><i style={{background:'#b99cf4'}}/>Thermal</span></div><div className="hint">Drag to orbit · scroll to zoom</div></div></div>
     <div className="panel timeline"><div className="timeline-top"><div className="playcontrols"><span className="clock">{clock(time)}</span><button className="btn icon" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause/>:<Play/>}</button>{[5,10,30].map(v=><button key={v} className={`btn ${speed===v?'primary':''}`} onClick={()=>setSpeed(v)}>{v}×</button>)}</div><div><span className="badge">Flex event {clock(config.start)} · {config.duration} min</span></div></div><Slider aria-label="Simulation time" min={0} max={1439} step={1} value={[time]} onValueChange={([v])=>{setTime(v);setPlaying(false)}}/><div className="timeline-times"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:59</span></div></div>
     <div className="panel chart-panel"><div className="chart-header"><div><h2>Grid trajectory</h2><small>Baseline demand versus energy-hub dispatch and recovery</small></div><span className="badge">PCC import kW</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid stroke="#24333e" vertical={false}/><XAxis dataKey="time" minTickGap={70}/><YAxis width={42}/><Tooltip contentStyle={{background:'#13202a',border:'1px solid #344957'}}/><ReferenceLine y={config.grid} stroke="#f68b81" strokeDasharray="5 4"/><Line type="monotone" dataKey="baseline" stroke="#758a9a" dot={false} strokeWidth={1.4}/><Line type="monotone" dataKey="controlled" stroke="#70e3bb" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div></div>
    </section>
    <aside className="right-panel"><div className="panel panel-body"><div className="section-label">Operational assets</div>{frame.assets.map(a=>{const Icon=assetIcon(a.kind);return <button className={`asset ${selected===a.id?'asset-selected':''}`} key={a.id} onClick={()=>setSelected(a.id)}><span className="asset-icon"><Icon/></span><span><div className="asset-title">{a.name}</div><div className={`asset-sub ${statusClass(a.state)}`}>{a.state.toUpperCase()}</div></span><span className="asset-reading">{n(a.availableDownKw,0)} kW<small>{n(a.sustainableMinutes,0)} min</small></span></button>})}</div><div className="panel panel-body" style={{marginTop:16}}><div className="section-label">{selectedAsset?selectedAsset.name:'Energy hub'}</div>{selectedAsset?<><Stat label="Current power" value={`${n(selectedAsset.currentKw)} kW`}/><Stat label="Available down-flex" value={`${n(selectedAsset.availableDownKw)} kW`}/><Stat label="Dispatched" value={`${n(selectedAsset.dispatchedKw)} kW`}/><Stat label="Sustainable" value={`${n(selectedAsset.sustainableMinutes,0)} min`}/><Stat label="Telemetry age" value={`${n(selectedAsset.telemetryAgeSec,0)} s`}/><div className="reason">{selectedAsset.reason}</div></>:<><Stat label="5 min envelope" value={`${n(frame.envelope5,0)} kW`}/><Stat label="15 min envelope" value={`${n(frame.envelope15,0)} kW`}/><Stat label="30 min envelope" value={`${n(frame.envelope30,0)} kW`}/><Stat label="60 min envelope" value={`${n(frame.envelope60,0)} kW`}/><Stat label="Telemetry quality" value={frame.telemetryQuality}/><div className="reason">A flexibility promise is defined by power and duration. The hub withdraws capacity when asset constraints or data quality make delivery uncertain.</div></>}</div></aside>
   </div>
   <section className="below"><Tabs value={tab} onValueChange={setTab}><TabsList className="tabsbar" variant="line"><TabsTrigger value="operations"><Activity/>Flex event</TabsTrigger><TabsTrigger value="envelope"><Layers3/>Flexibility envelope</TabsTrigger><TabsTrigger value="alarms"><AlertTriangle/>Thresholds & alarms</TabsTrigger><TabsTrigger value="model"><Info/>Model & assumptions</TabsTrigger></TabsList>
    <TabsContent value="operations"><div className="operations-grid"><div className="panel chart-panel"><div className="chart-header"><div><h2>Commitment, delivery and rebound</h2><small>The deferred load is explicitly restored after the event</small></div><span className={`badge ${compliance<98?'red':'green'}`}>{n(compliance,1)}% energy delivered</span></div><div className="chart" style={{height:260}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={eventData}><CartesianGrid stroke="#24333e" vertical={false}/><XAxis dataKey="time"/><YAxis/><Tooltip contentStyle={{background:'#13202a',border:'1px solid #344957'}}/><Area type="monotone" dataKey="request" stroke="#91a7fc" fill="#91a7fc22"/><Area type="monotone" dataKey="delivered" stroke="#70e3bb" fill="#70e3bb22"/><Area type="monotone" dataKey="rebound" stroke="#f6c66b" fill="#f6c66b11"/></AreaChart></ResponsiveContainer></div></div><div className="panel panel-body"><div className="eyebrow">EVENT SCORECARD</div><h2>What the promise actually means</h2><Stat label="Requested flex energy" value={`${n(requestedKwh,1)} kWh`}/><Stat label="Delivered flex energy" value={`${n(deliveredKwh,1)} kWh`}/><Stat label="Compliance" value={`${n(compliance,1)} %`}/><Stat label="Deferred load now" value={`${n(frame.deferredKwh,1)} kWh`}/><Stat label="Recovered so far" value={`${n(frame.recoveredKwh,1)} kWh`}/><Stat label="Battery" value={`${n(frame.batterySoc,0)}% · ${n(frame.batteryTemp,1)} °C`}/><Stat label="Cold store" value={`${n(frame.coldTemp,1)} °C`}/><div className="callout">The model never treats curtailed demand as free energy. EV, cold-store and HVAC reductions accumulate as deferred demand and are restored under the import ceiling after the event.</div></div></div></TabsContent>
    <TabsContent value="envelope"><div className="envelope-grid"><div className="panel panel-body"><div className="eyebrow">POWER × DURATION</div><h2>Current flexibility envelope</h2>{[[5,frame.envelope5],[15,frame.envelope15],[30,frame.envelope30],[60,frame.envelope60]].map(([mins,kw])=><div className="envelope-row" key={mins}><span>{mins} min</span><div className="envelope-track"><i style={{width:`${Math.min(100,Number(kw)/140*100)}%`}}/></div><b>{n(Number(kw),0)} kW</b></div>)}<div className="callout">Capacity falls with duration because battery energy, EV deadlines and thermal buffers are finite. This is why a single “available kW” number is not enough for a commercial flexibility commitment.</div></div><div className="panel panel-body"><div className="eyebrow">ASSET DISPATCH</div><h2>Dispatch at {clock(time)}</h2>{dispatchData.map((d,i)=><div className="dispatch-row" key={d.name}><span>{d.name}</span><div className="dispatch-bars"><i className="available" style={{width:`${Math.min(100,d.available/110*100)}%`}}/><i className="used" style={{width:`${Math.min(100,d.dispatch/110*100)}%`}}/></div><b>{n(d.dispatch,0)} / {n(d.available,0)} kW</b></div>)}<small>Bright segment = dispatched · muted segment = currently available.</small></div></div></TabsContent>
    <TabsContent value="alarms"><div className="panel"><div className="panel-head"><div><h2>Operational log through {clock(time)}</h2><small>Thresholds, quality state and redispatch events</small></div><span className="badge">Newest first</span></div><div className="events">{alarms.length?alarms.map((e,i)=><div className="event" key={`${e.time}-${i}`}><time>{clock(e.time)}</time><span className={e.severity==='critical'?'red':e.severity==='warning'?'amber':e.severity==='success'?'green':''}>{e.text}</span><small>{e.asset}</small></div>):<div className="empty">No hub events yet. Advance to the flexibility window.</div>}</div></div></TabsContent>
    <TabsContent value="model"><div className="panel assumptions"><div><h2>V2 keeps V1 and adds an orchestration layer</h2><p>The original BEMS engine remains untouched and is still available at <b>/v1</b>. V2 uses its deterministic building, solar, EV-arrival and charging results as the site baseline, then adds an energy-hub control layer with a BESS, cold-store thermal buffer, flexibility commitment, telemetry quality, thresholds and recovery.</p><p>The objective is product and operational discovery: can a commercial site make a flexibility promise, explain which assets support it, protect customer and comfort constraints, detect when the promise degrades and show the rebound that follows?</p><h2 style={{marginTop:20}}>Deliberate limits</h2><p>Aggregate active power only. No three-phase load-flow, protection coordination, battery electrochemistry, real OCPP/Modbus/BACnet connection or market settlement engine. The control logic is deterministic and transparent rather than an optimisation claim.</p></div><div><h2>Threshold-oriented operator model</h2><p>Each asset publishes current power, available down-flex, sustainable duration, telemetry age, operating state and a reason. BESS temperature can derate discharge, cold-store temperature protects product conditions, EV flexibility is bounded by declared departure energy and stale telemetry withdraws uncertain capacity.</p><Stat label="BESS operating energy" value="24–114 kWh"/><Stat label="BESS nominal capacity" value="120 kWh"/><Stat label="Cold-store protected boundary" value="−16 °C"/><Stat label="Telemetry stale threshold" value=">120 s"/><Stat label="Recovery policy" value="Below site import ceiling"/><button className="btn" onClick={()=>{setConfig(flexDefaults);setTime(765);setSelected('hub');setPlaying(false)}}><RotateCcw/>Restore V2 defaults</button></div></div></TabsContent>
   </Tabs></section>
   <footer className="footer"><span>FUTURE EV / ENERGY TWIN · V2</span><span>V1 preserved · synthetic deterministic data · product-discovery model</span></footer>
  </main>
 </div>
}
