"use client";
import {useEffect,useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import {Activity,BrainCircuit,Car,Clock3,Euro,Leaf,Pause,Play,RotateCcw,ShieldCheck,SlidersHorizontal,Waypoints,Zap} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {LineChart,Line,BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,ReferenceLine} from 'recharts';
import {clock} from '@/lib/twin/engine';
import {compareStrategies,markets,optimizerDefaults,simulateOptimizer,strategies,type Market,type OptimizerConfig,type OptimizerStrategy} from '@/lib/twin/optimizer-engine';
const SiteScene=dynamic(()=>import('./SiteScene'),{ssr:false,loading:()=> <div className="error-fallback">Preparing the digital twin…</div>});
const n=(v:number,d=1)=>v.toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d});
function Metric({label,value,unit,note,icon:Icon,color=''}:any){return <div className="metric"><div className="metric-label">{label}<Icon/></div><div className={`metric-value ${color}`}>{value}<span>{unit}</span></div><div className="metric-note">{note}</div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="inspector-stat"><span>{label}</span><b>{value}</b></div>}
export default function OptimizerApp(){
 const [config,setConfig]=useState<OptimizerConfig>(optimizerDefaults),[time,setTime]=useState(480),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(20),[selected,setSelected]=useState('site'),[reset,setReset]=useState(0);
 const result=useMemo(()=>simulateOptimizer(config),[config]);const comparisons=useMemo(()=>compareStrategies(config),[config.market,config.grid,config.solar,config.chargers,config.seed,config.peakThreshold,config.carbonWeight,config.flexWeight]);const frame=result.frames[Math.floor(time)];
 useEffect(()=>{if(!playing)return;let last=performance.now();const id=setInterval(()=>{const now=performance.now(),dt=(now-last)/1000;last=now;setTime(t=>{const x=t+dt*speed;if(x>=1439){setPlaying(false);return 1439}return x})},50);return()=>clearInterval(id)},[playing,speed]);
 const patch=(p:Partial<OptimizerConfig>)=>{setConfig(c=>({...c,...p}));setPlaying(false)};
 const qdata=result.quarters.map(x=>({time:x.time,price:+(x.price*100).toFixed(1),ev:+x.plannedEv.toFixed(1),grid:+x.projectedGrid.toFixed(1),carbon:+x.carbon.toFixed(0)}));
 const selectedId=selected.startsWith('car:')?Number(selected.split(':')[1]):-1,vehicle=result.vehicles[selectedId],car=frame.cars[selectedId];
 return <div className="shell optimizer-v3"><header className="header"><div className="brand"><div className="brandmark"><BrainCircuit/></div><div><div className="brandname">FUTURE EV / <span>ENERGY TWIN</span></div><small>V3 · Explainable smart-charging optimizer</small></div><div className="divider"/><span className="badge">15-MIN MPC</span></div><div className="header-actions"><a className="btn" href="./v1/">V1 BEMS</a><a className="btn" href="./v2/">V2 Flex hub</a></div></header>
 <main className="workspace"><div className="intro"><div><div className="eyebrow">MARKET → OPTIMIZER → PHYSICAL TWIN</div><h1>Watch the same fleet make different decisions under different objectives</h1><p>96 quarter-hour decisions combine tariff signals, site headroom, vehicle deadlines and operational priorities.</p></div><div className="intro-right"><span className="status-tag"><i/>Deterministic plan active</span></div></div>
 <div className="metrics"><Metric label="Total modeled cost" value={`€${n(result.scorecard.totalCost,0)}`} note={`Energy €${n(result.scorecard.energyCost,0)} + peak €${n(result.scorecard.peakCost,0)}`} icon={Euro}/><Metric label="Site peak" value={n(result.scorecard.peak,0)} unit="kW" note={`Protected threshold ${config.peakThreshold} kW`} icon={Waypoints} color={result.scorecard.peak>config.peakThreshold?'amber':'green'}/><Metric label="Departure success" value={n(result.scorecard.readyPct,0)} unit="%" note={`${result.final.ready} targets met · ${n(result.final.shortfall,1)} kWh short`} icon={ShieldCheck} color={result.scorecard.readyPct>95?'green':'amber'}/><Metric label="Operational carbon" value={n(result.scorecard.carbonKg,0)} unit="kg" note="Illustrative time-varying intensity" icon={Leaf}/><Metric label="Stress-window headroom" value={n(result.scorecard.flexHeadroom,0)} unit="kW" note="Average preserved import capacity" icon={Activity}/></div>
 <div className="main-grid"><aside className="left-panel"><div className="panel panel-body"><div className="section-label">Optimizer objective</div>{strategies.map(s=><button key={s.id} className={`scenario-choice ${config.strategy===s.id?'active':''}`} onClick={()=>patch({strategy:s.id})}><b>{s.name}</b><span>{s.description}</span></button>)}<div className="sepline"/><div className="section-label">Market / tariff profile</div><Select value={config.market} onValueChange={v=>patch({market:v as Market})}><SelectTrigger className="select"><SelectValue/></SelectTrigger><SelectContent>{markets.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select><p className="scenario-note">{markets.find(m=>m.id===config.market)?.note}</p><div className="field"><label>Grid connection <b>{config.grid} kW</b></label><Slider min={70} max={220} step={5} value={[config.grid]} onValueChange={([grid])=>patch({grid})}/></div><div className="field"><label>Protected peak <b>{config.peakThreshold} kW</b></label><Slider min={50} max={180} step={5} value={[config.peakThreshold]} onValueChange={([peakThreshold])=>patch({peakThreshold})}/></div><div className="field"><label>Solar peak <b>{config.solar} kWp</b></label><Slider min={0} max={160} step={5} value={[config.solar]} onValueChange={([solar])=>patch({solar})}/></div></div></aside>
 <section className="centre"><div className="scene-panel"><SiteScene frame={frame} vehicles={result.vehicles} time={time} roof={true} flows={true} reset={reset} battery={false} chargers={config.chargers} onSelect={setSelected}/><div className="scene-top"><div><div className="scene-title">Optimizer-controlled site · {markets.find(m=>m.id===config.market)?.name}</div><div className="scene-sub">{strategies.find(s=>s.id===config.strategy)?.name} · click a vehicle for its decision</div></div><div className="scene-tools"><button className="btn icon" onClick={()=>setReset(v=>v+1)}><RotateCcw/></button></div></div><div className="scene-bottom"><div className="legend"><span><i style={{background:'#70e3bb'}}/>Charging</span><span><i style={{background:'#f6c66b'}}/>Deferred</span></div><div className="hint">The 3D twin reads the optimizer result</div></div></div>
 <div className="panel timeline"><div className="timeline-top"><div className="playcontrols"><span className="clock">{clock(time)}</span><button className="btn icon" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause/>:<Play/>}</button>{[10,20,60].map(v=><button key={v} className={`btn ${speed===v?'primary':''}`} onClick={()=>setSpeed(v)}>{v}×</button>)}</div><span className="badge">Quarter {Math.floor(time/15)+1}/96</span></div><Slider min={0} max={1439} step={1} value={[time]} onValueChange={([v])=>{setTime(v);setPlaying(false)}}/><div className="timeline-times"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:59</span></div></div>
 <div className="panel chart-panel"><div className="chart-header"><div><h2>96-quarter plan</h2><small>Projected grid import and protected peak</small></div><span className="badge">kW</span></div><div className="chart" style={{height:220}}><ResponsiveContainer width="100%" height="100%"><LineChart data={qdata}><CartesianGrid stroke="#24333e" vertical={false}/><XAxis dataKey="time" minTickGap={60}/><YAxis/><Tooltip contentStyle={{background:'#13202a',border:'1px solid #344957'}}/><ReferenceLine y={config.peakThreshold} stroke="#f6c66b" strokeDasharray="5 4"/><Line dataKey="grid" stroke="#70e3bb" dot={false} strokeWidth={2}/><Line dataKey="ev" stroke="#91a7fc" dot={false}/></LineChart></ResponsiveContainer></div></div></section>
 <aside className="right-panel"><div className="panel panel-body"><div className="section-label">{vehicle?vehicle.name:'Decision inspector'}</div>{vehicle&&car?<><Stat label="State" value={car.status}/><Stat label="Power now" value={`${n(car.power,1)} kW`}/><Stat label="Delivered" value={`${n(car.delivered,1)} / ${n(vehicle.need,0)} kWh`}/><Stat label="Departure" value={clock(vehicle.departure)}/><Stat label="Max AC" value={`${vehicle.maxKw} kW`}/><div className="reason">{car.reason}<br/><br/>{result.explanations[vehicle.id]}</div></>:<><h2>Why is a charger on or off?</h2><p className="scenario-note">Select a vehicle in the 3D scene. The inspector exposes its current allocation, target, deadline and the optimizer's plan.</p><Stat label="Current retail signal" value={`€${n(result.quarters[Math.floor(time/15)].price,3)}/kWh`}/><Stat label="Carbon intensity" value={`${n(result.quarters[Math.floor(time/15)].carbon,0)} g/kWh`}/><Stat label="Planned EV load" value={`${n(result.quarters[Math.floor(time/15)].plannedEv,0)} kW`}/><Stat label="Projected grid" value={`${n(result.quarters[Math.floor(time/15)].projectedGrid,0)} kW`}/></>}</div></aside></div>
 <section className="below"><div className="panel chart-panel"><div className="chart-header"><div><h2>Strategy comparison — identical fleet and site</h2><small>Change only the objective function; physical assumptions remain constant</small></div><span className="badge">MODELED RESULTS</span></div><div className="strategy-grid">{comparisons.map(x=><button key={x.strategy} className={`compare-card panel ${config.strategy===x.strategy?'active':''}`} onClick={()=>patch({strategy:x.strategy as OptimizerStrategy})}><h3>{x.name}</h3><div className="hero-number">€{n(x.result.scorecard.totalCost,0)}</div><div className="compare-row"><span>Peak</span><b>{n(x.result.scorecard.peak,0)} kW</b></div><div className="compare-row"><span>Targets</span><b>{n(x.result.scorecard.readyPct,0)}%</b></div><div className="compare-row"><span>CO₂</span><b>{n(x.result.scorecard.carbonKg,0)} kg</b></div></button>)}</div></div>
 <div className="optimizer-bottom"><div className="panel chart-panel"><div className="chart-header"><div><h2>Market signal and charging response</h2><small>Price is modeled in euro-cents/kWh; EV load is kW</small></div></div><div className="chart" style={{height:250}}><ResponsiveContainer width="100%" height="100%"><BarChart data={qdata}><CartesianGrid stroke="#24333e" vertical={false}/><XAxis dataKey="time" minTickGap={55}/><YAxis/><Tooltip contentStyle={{background:'#13202a',border:'1px solid #344957'}}/><Bar dataKey="price" fill="#f6c66b"/><Bar dataKey="ev" fill="#70e3bb"/></BarChart></ResponsiveContainer></div></div><div className="panel panel-body"><div className="eyebrow">WHAT THIS MODEL DOES</div><h2>Rolling-control architecture, transparent assumptions</h2><p className="scenario-note">The planner allocates each EV's required energy across the 96 quarter-hours in which that vehicle is present. It respects charger power, site import capacity and departure energy. Objectives change the score assigned to each feasible interval. A feasibility-recovery pass fills remaining physical headroom when the preferred plan cannot meet a deadline.</p><div className="callout">Market and carbon curves in this prototype are synthetic demonstration signals, not live EPEX or settlement data. Jurisdiction profiles demonstrate tariff mechanics and are intentionally separated from the physical simulation so real tariff adapters can replace them later.</div></div></div></section>
 <footer className="footer"><span>FUTURE EV / ENERGY TWIN · V3 OPTIMIZER</span><span>96 × 15 min · explainable allocations · synthetic market data</span></footer></main></div>;
}