import {clock,simulate,type Config,type Frame,type Result} from './engine';
export type AdvancedPolicy='cheap'|'peak'|'total';
export type Market='nl'|'flanders'|'wallonia'|'brussels';
export type OptimizerConfig={policy:AdvancedPolicy;market:Market;peak:number};
export const optimizerDefaults:OptimizerConfig={policy:'total',market:'nl',peak:85};
export const advancedPolicies=[{id:'cheap' as const,name:'Cheapest energy',description:'Uses the cheapest feasible quarter-hours before each departure.'},{id:'peak' as const,name:'Peak-aware',description:'Avoids creating a new site peak when vehicles have time to wait.'},{id:'total' as const,name:'Total-cost optimizer',description:'Balances tariff, peak exposure, site headroom and departure urgency.'}];
export const markets=[{id:'nl' as const,name:'Netherlands'},{id:'flanders' as const,name:'Flanders'},{id:'wallonia' as const,name:'Wallonia'},{id:'brussels' as const,name:'Brussels'}];
const wholesale=(t:number)=>.075+.055*Math.sin((t/60-7)/24*Math.PI*2)+.045*Math.exp(-Math.pow((t/60-19)/2.3,2))-.035*Math.exp(-Math.pow((t/60-13)/2.5,2));
const network=(m:Market,t:number)=>{const h=t/60;if(m==='wallonia')return (h>=11&&h<17)||(h>=22||h<7)?.025:.085;if(m==='brussels')return h>=7&&h<22?.065:.028;return .035};
export const retail=(m:Market,t:number)=>Math.max(.02,wholesale(t)+.095+network(m,t));
export type OptimizerResult=Result&{optimizer:OptimizerConfig;baseline:Result;score:{energy:number;peakCost:number;total:number;peak:number;readyPct:number};explanations:Record<number,string>};
export function simulateOptimized(baseConfig:Config,opt:OptimizerConfig):OptimizerResult{
 const baseline=simulate({...baseConfig,policy:'balanced',battery:false}),vehicles=baseline.vehicles,cars=vehicles.map(v=>({id:v.id,bay:-1,parkedAt:-1,delivered:0,power:0,status:'Expected',reason:'Not on site yet'})),events=[] as Result['events'],frames=[] as Frame[];
 let cost=0,imp=0,exp=0,del=0,peak=0,ready=0,departed=0,shortfall=0;const plans=vehicles.map(()=>new Array(96).fill(0)),quarterLoad=new Array(96).fill(0);
 // Plan each connected vehicle across feasible 15-minute windows. V1 remains the physical/site baseline.
 for(const v of [...vehicles].sort((a,b)=>a.departure-b.departure)){let need=v.need/.9;const start=Math.ceil((v.arrival+2)/15),end=Math.floor((v.departure-1)/15);const candidates=[] as {q:number;score:number}[];for(let q=start;q<=end;q++){const t=q*15,b=baseline.frames[t],projected=b.building-b.solar+quarterLoad[q],p=retail(opt.market,t),peakPenalty=Math.max(0,projected-opt.peak);let score=p;if(opt.policy==='peak')score=peakPenalty*2+p*.2;if(opt.policy==='total')score=p+peakPenalty*(opt.market==='flanders'?2.5:.8);candidates.push({q,score});}candidates.sort((a,b)=>a.score-b.score||a.q-b.q);for(const x of candidates){if(need<=.001)break;const b=baseline.frames[x.q*15],head=Math.max(0,baseConfig.grid-b.building+b.solar-quarterLoad[x.q]);let preferred=head;if(opt.policy!=='cheap')preferred=Math.min(preferred,Math.max(0,opt.peak-b.building+b.solar-quarterLoad[x.q]));let kw=Math.min(v.maxKw,preferred),kwh=Math.min(need,kw*.25);if(kwh<.05)continue;plans[v.id][x.q]=kwh/.25;quarterLoad[x.q]+=kwh/.25;need-=kwh;}if(need>.001)for(let q=start;q<=end&&need>.001;q++){const b=baseline.frames[q*15],head=Math.max(0,baseConfig.grid-b.building+b.solar-quarterLoad[q]),kw=Math.min(v.maxKw,head),kwh=Math.min(need,kw*.25);plans[v.id][q]+=kwh/.25;quarterLoad[q]+=kwh/.25;need-=kwh;}}
 const explanations:Record<number,string>={};vehicles.forEach(v=>{const qs=plans[v.id].map((p,q)=>({p,q})).filter(x=>x.p>0);explanations[v.id]=qs.length?`Planned in ${qs.length} quarter-hours between ${clock(qs[0].q*15)} and ${clock((qs.at(-1)!.q+1)*15)} to deliver ${v.need} kWh before ${clock(v.departure)}.`:'No feasible allocation found.'});
 for(let t=0;t<1440;t++){const bf=baseline.frames[t],q=Math.floor(t/15);for(const v of vehicles){const s=cars[v.id];s.power=0;if(t===v.arrival){s.status='Queued';s.reason='Waiting for a free charging space';}if(t===v.departure){s.status='Departed';departed++;const gap=Math.max(0,v.need-s.delivered);shortfall+=gap;if(gap<.05)ready++;}if(t<v.arrival||t>=v.departure)continue;const used=new Set(cars.filter(x=>x.id!==s.id&&x.bay>=0&&x.status!=='Departed'&&x.status!=='Expected').map(x=>x.bay));if(s.bay<0){let bay=0;while(used.has(bay)&&bay<baseConfig.chargers)bay++;if(bay<baseConfig.chargers){s.bay=bay;s.parkedAt=t;s.status='Arriving';s.reason='Driving to assigned charger';}}if(s.bay<0)continue;if(t<s.parkedAt+2)continue;const remaining=Math.max(0,v.need-s.delivered);if(remaining<.001){s.status='Ready';s.reason='Requested energy delivered · parked until departure';continue;}s.power=Math.min(plans[v.id][q],v.maxKw,remaining*60/.9);if(s.power>0){s.status='Charging';s.reason=opt.policy==='cheap'?'Low-cost quarter selected':opt.policy==='peak'?'Charging without exceeding the preferred peak':'Best total-cost quarter given price, peak and deadline';}else{s.status='Paused';s.reason='Deferred by optimizer; departure target remains feasible';}const add=s.power*.9/60;s.delivered+=add;del+=add;}
 const ev=cars.reduce((a,s)=>a+s.power,0),grid=bf.building+ev-bf.solar;imp+=Math.max(0,grid)/60;exp+=Math.max(0,-grid)/60;cost+=(Math.max(0,grid)*retail(opt.market,t)-Math.max(0,-grid)*.07)/60;peak=Math.max(peak,grid);frames.push({...bf,ev,grid,limit:baseConfig.grid,price:retail(opt.market,t),cars:cars.map(s=>({...s})),ready,departed,shortfall,cost,importKwh:imp,exportKwh:exp,delivered:del,peak,violations:grid>baseConfig.grid?1:0,excess:Math.max(0,grid-baseConfig.grid)/60,queue:cars.filter(s=>s.status==='Queued').length});}
 const peakCost=opt.market==='flanders'?Math.max(0,peak-opt.peak)*4.45:Math.max(0,peak-opt.peak)*1.2;return{config:baseConfig,vehicles,frames,events,final:frames[1439],optimizer:opt,baseline,score:{energy:cost,peakCost,total:cost+peakCost,peak,readyPct:vehicles.length?ready/vehicles.length*100:100},explanations};
}
